config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  get 'welcome/index'
  resources "habits"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  validates :title, :description, :category, presence: true  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :habits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  def index
    @habits = Habit.where(user_id:current_user.id)
  end

  def show
    @habit = Habit.find(params["id"])
  end

  def edit
    @habit = Habit.find(params["id"])
  end

  def update
    habit_params = params["habit"].permit("title", "description", "category", "date")
    habit = Habit.find(params["id"])
    habit.update(habit_params)
    redirect_to(habit_path(habit))
  end

  def create    
    habit_params = params["habit"].permit("title", "description", "category", "date").merge(user_id: current_user.id)
    habit = Habit.create(habit_params)
    redirect_to(habit_path(habit))
  end

  def destroy
    @habit = Habit.find(params["id"])
    @habit.destroy
    redirect_to(habits_path)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @habits = Habit.all
    @websites = [
      ["http://railsgirls.com", "Rails Girls"],
      ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
      ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/habits/edit.html.erb
<div class="container">
  <br>
  <%= form_for(@habit) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("title") %></p>
    <p><%= form.label("description") %></p>
    <p><%= form.text_area("description") %></p>
    <p><%= form.label("category") %></p>
    <p><%= form.text_field("category") %></p>
    <p><%= form.label("date") %></p>
    <p><%= form.date_field("date") %></p>
    <p><%= form.submit %></p>
  <% end %>
  <br>
  <p><%= link_to("Back to this habit", habit_path(@habit)) %></p>
  <p><%= link_to("Back to all habits", habits_path) %></p>
</div>

app/views/habits/index.html.erb
<div class="container">
  <h2>My Habits:</h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th> 
        <th>Category</th>
        <th>Date</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% for habit in @habits %>
      <tr>
      <td><%= link_to(habit.title, habit_path(habit)) %></td>      
      <td><%= habit.description %></td>
      <td><%= habit.category %></td>
      <td>Date: <%= habit.date %></td>
      <td><button type="button" class="btn btn-danger"><%= link_to("Destroy", habit, method: :delete, data: { confirm: 'sure?'}) %></button></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <button type="button" class="btn btn-primary"><%= link_to("New habit", new_habit_path) %></button>
  
</div>

app/views/habits/new.html.erb
<div class="container">
  <br>
  <%= form_for(Habit.new) do |form| %>
    <p><%= form.label("title") %></p>
    <p><%= form.text_field("title") %></p>
    <p><%= form.label("description") %></p>
    <p><%= form.text_area("description") %></p>
    <p><%= form.label("category") %></p>
    <p><%= form.text_field("category") %></p>
    <p><%= form.label("date") %></p>
    <p><%= form.date_field("date") %></p>
    <p><%= form.submit %></p>
  <% end %>
  <br>
  <p><%= link_to("Back to all habits", habits_path) %></p>
</div>

app/views/habits/show.html.erb
<div class="container">
  <h2>Title: <%= @habit.title %></h2> 
  <p>Description: <%= @habit.description %></p>
  <p>Category: <%= @habit.category %></p>
  <p>Date: <%= @habit.date %></p>

  <p><%= link_to("Edit this habit", edit_habit_path(@habit)) %></p>

  <p><%= link_to("Back to my habits", habits_path) %></p>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Habits Tracker", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right"> 
        <% if user_signed_in? %>
          <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li>
          <%= link_to('Login', new_user_session_path) %>  
          </li>
        <% end %>
      </ul>

    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Habits Tracker</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <div class="text-center">
    <h1><%= link_to("Start tracking habits!", habits_path) %></h1>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome To Your Habits Tracker</h1>

    <h2>Track your activities, create positive habits!</h2>
    <%= link_to "Sign up now!", 'users/sign_up', class: "btn btn-lg btn-primary" %>
    
  </div>
  <br>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h4>"HabitsTracker made me superproductive!"</h4>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <p class="text-left">-John Doe</p>
      </div>
      <div class="col-md-4">
        <h4>"Can't live without HabitsTracker"</h4>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <p class="text-left">-John Doe</p>
      </div>
      <div class="col-md-4">
        <h4>"HabitsTracker has made my life easier."</h4>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
        <p class="text-left">-Patrick Larose</p>
      </div>
    </div>
  </div>
<% end %>